name:                hs-google-signin
version:             0.1.0.0
github:              "jkaye2012/hs-google-signin"
license:             BSD3
author:              "Jordan Kaye"
maintainer:          "jordan.kaye2@gmail.com"
copyright:           "2020 Jordan Kaye"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jkaye2012/hs-google-signin#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.10.0 && < 1
- containers >= 0.4 && < 1
- either >= 5.0.1.1 && < 6
- http-conduit >= 2.3 && < 3
- http-types >= 0.12.0 && < 1
- jwt >= 0.10 && < 1
- mtl >= 2.2.2 && < 3
- text >= 1.2.4.0 && < 2
- time >= 1.9.3 && < 2
- transformers >= 0.4.2.0 && < 1

library:
  source-dirs: src

executables:
  hs-google-signin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-google-signin

tests:
  hs-google-signin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-google-signin
